// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfqmGj84qHNo-gaJXUNhuroy5UeZBOuRA',
    appId: '1:757491665635:android:64eef1e1e8109ef46713d6',
    messagingSenderId: '757491665635',
    projectId: 'flutterboilerplate-prod',
    storageBucket: 'flutterboilerplate-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbn2bsPhF24XABlkZRTEmT1I6yP0vn4Bw',
    appId: '1:757491665635:ios:0a029da0b90ae0486713d6',
    messagingSenderId: '757491665635',
    projectId: 'flutterboilerplate-prod',
    storageBucket: 'flutterboilerplate-prod.appspot.com',
    iosClientId:
        '757491665635-gcuidbeugdbd78pj2933vpgh6av9e1d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterboilerplate',
  );
}
