// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_beta.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PRR2wQbDbb1i8YEg2-HjQEN1QlrONfI',
    appId: '1:735181552050:android:1712bb17858dbcae988cab',
    messagingSenderId: '735181552050',
    projectId: 'flutterboilerplate-beta',
    storageBucket: 'flutterboilerplate-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHOAHQNwR3XcOTKeYx9IyCGQHZrn3hCs',
    appId: '1:735181552050:ios:6bf7aae2cacc345c988cab',
    messagingSenderId: '735181552050',
    projectId: 'flutterboilerplate-beta',
    storageBucket: 'flutterboilerplate-beta.appspot.com',
    iosClientId:
        '735181552050-3g15t0ns692vjj0e5qvpjc2oa8ttmav7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterboilerplate',
  );
}
