// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVkWMhuS1ETtIj68oLn6SEZf5UEGhwyH4',
    appId: '1:303362090433:android:fc4bf0a1e112797e723b40',
    messagingSenderId: '303362090433',
    projectId: 'flutterboilerplate-dev',
    storageBucket: 'flutterboilerplate-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2S7dImhtsHqwzk0aTxoyhHuhJ-EXZi0',
    appId: '1:303362090433:ios:408724802f611b8b723b40',
    messagingSenderId: '303362090433',
    projectId: 'flutterboilerplate-dev',
    storageBucket: 'flutterboilerplate-dev.appspot.com',
    iosClientId:
        '303362090433-u72c5mdqd0fuqjt06ro3l5t701pro30h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterboilerplate',
  );
}
